### PR TITLE
feat: HomePage

### PR DESCRIPTION
**Pull request by jDineshKarthic**
Contains the code for my Home Page

### CODE REVIEW

**Comment by aliamaanansari** [comment]
looks Great! , didn't find any  mistake!, Naming is done quite good and its flexible bcz ur using rem and roots element !

**Comment by jDineshKarthic** [comment]
Thanks for your feedback Ali

**Review by nakulsharma15 — APPROVED** [review]
Looks good to me. Liked the way you named your variables and file structure

**Comment by jDineshKarthic** [comment]
Thanks nakul

**Pull request merged**
